teleop_twist_joy:
  ros__parameters:
    enable_button: 7
    require_enable_button: true

    publish_stamped_twist: true

    axis_linear:
      x: 3

    axis_angular:
      yaw: 0

    scale_linear:
      x: 0.5

    scale_angular:
      yaw: 0.5

    deadzone: 0.2