#!/usr/bin/env python3
"""Load the real-world test paths generated by scripts/test_paths/generate_test_paths.py.

Those CSVs are the five reference courses (straight_line, lane_change, circle,
circle_transition, infinity) used to validate path tracking on the physical
rover -- the same five that validate rover_nav's `omar` branch in simulation,
so a result here is directly comparable to one there.

Frame: every CSV is in a *rover-start-relative* frame -- origin (0, 0) is the
rover's launch point, +x its initial heading, +y to its left. On this branch
that is exactly what `odom` is: imu_yaw_zero.py zeroes fused yaw at the first
IMU sample, so the EKF's odom frame starts at the rover's own launch pose
facing +x. That means a test path needs no map->odom alignment (unlike
WAYPOINTS in global_path_planner.py, which are in the competition's map
frame) -- it is either driven as-is in odom (`anchor="odom_origin"`), or
rigidly re-anchored to wherever the rover actually is when the run starts
(`anchor="start_pose"`, the default -- see anchor_path()).

Kept stdlib-only (no rclpy, numpy, or hardware imports) so the same loader
serves the ROS nodes, the offline plotting tools, and the tests.

CLI:
  python3 test_path_loader.py --list
  python3 test_path_loader.py --info circle
"""

import csv
import math
import os

# Name -> one-line description of what each course actually tests. Keys are
# the CSV basenames written by generate_test_paths.py.
TEST_PATHS = {
    "straight_line": "Straight-line tracking -- 12 m long",
    "lane_change": "Lane change: 3.2 m straight, 4.8 m shift of 1.6 m, 3.2 m straight",
    "circle": "Constant-curvature tracking -- 5.0 m radius loop (~31 m around)",
    "circle_transition": "Curvature step -- one 3.0 m loop into one 6.0 m loop",
    "infinity": "Figure-8 -- lemniscate with 5.0 m lobes, self-crossing at the origin",
}

# Search order for the CSVs: the installed share/ copy first (what a running
# ROS node sees), then the source tree next to the generator (so the offline
# tools work in a workspace that was never built).
_SOURCE_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "test_paths", "output")


def _share_dir():
    try:
        from ament_index_python.packages import get_package_share_directory
        return os.path.join(get_package_share_directory("rover_nav"), "test_paths")
    except Exception:
        return None


def search_dirs():
    dirs = []
    env_dir = os.environ.get("ROVER_NAV_TEST_PATH_DIR")
    if env_dir:
        dirs.append(env_dir)
    share = _share_dir()
    if share:
        dirs.append(share)
    dirs.append(_SOURCE_DIR)
    return dirs


def available():
    """Names that actually have a CSV on disk right now, in TEST_PATHS order."""
    found = []
    for name in TEST_PATHS:
        for d in search_dirs():
            if os.path.isfile(os.path.join(d, f"{name}.csv")):
                found.append(name)
                break
    return found


def _find_csv(filename):
    tried = []
    for d in search_dirs():
        candidate = os.path.join(d, filename)
        tried.append(candidate)
        if os.path.isfile(candidate):
            return candidate
    raise FileNotFoundError(
        f"{filename} not found. Generate it with:\n"
        f"  python3 {os.path.join(os.path.dirname(_SOURCE_DIR), 'generate_test_paths.py')}\n"
        f"then rebuild rover_nav so it lands in share/. Looked in: {', '.join(tried)}"
    )


def load_test_path(name):
    """Dense waypoints of test path `name` as [[x, y], ...] (metres, path frame).

    Yaw is deliberately dropped: pure pursuit derives heading from the
    geometry it is chasing, and carrying a per-point yaw the follower ignores
    invites it being trusted somewhere it isn't actually enforced. Use
    load_test_path_yaw() where the reference heading itself is wanted (plots,
    tracking-error analysis)."""
    return [[x, y] for x, y, _ in load_test_path_yaw(name)]


def load_test_path_yaw(name):
    """As load_test_path(), but [[x, y, yaw_rad], ...]."""
    if name not in TEST_PATHS:
        raise KeyError(f"unknown test path '{name}'. Known: {', '.join(TEST_PATHS)}")
    points = []
    with open(_find_csv(f"{name}.csv"), newline="") as f:
        for row in csv.DictReader(f):
            points.append([float(row["x_m"]), float(row["y_m"]), float(row["yaw_rad"])])
    if len(points) < 2:
        raise ValueError(f"test path '{name}' has {len(points)} point(s) -- expected a dense path")
    return points


def load_markers(name):
    """Sparse ground markers as [(marker_id, x, y, yaw_rad), ...] -- the
    physical cone/stake positions to pace out before the run, and what the
    rover is judged on passing near."""
    if name not in TEST_PATHS:
        raise KeyError(f"unknown test path '{name}'. Known: {', '.join(TEST_PATHS)}")
    markers = []
    with open(_find_csv(f"{name}_markers.csv"), newline="") as f:
        for row in csv.DictReader(f):
            markers.append((
                int(row["marker_id"]),
                float(row["x_m"]),
                float(row["y_m"]),
                float(row["yaw_rad"]),
            ))
    return markers


def anchor_path(points, origin_xy, origin_yaw):
    """Rigidly place a path-frame point list at a pose in another frame.

    The CSVs assume the rover sits at the path's (0, 0) facing +x. That holds
    in odom only while the rover hasn't moved since localization started --
    which is not true if it was driven to the test site, or if a previous run
    already happened. Re-anchoring to the live pose at run start restores the
    assumption without restarting localization: rotate by the rover's current
    yaw, then translate to its current position, so path point (0, 0) lands
    under the rover and +x points wherever it is facing."""
    c, s = math.cos(origin_yaw), math.sin(origin_yaw)
    ox, oy = origin_xy[0], origin_xy[1]
    return [[p[0] * c - p[1] * s + ox, p[0] * s + p[1] * c + oy] for p in points]


def path_length(points):
    return sum(
        math.hypot(b[0] - a[0], b[1] - a[1])
        for a, b in zip(points, points[1:])
    )


def _main():
    import argparse

    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--list", action="store_true", help="List the test paths and their status")
    parser.add_argument("--info", metavar="NAME", help="Print stats and ground markers for one path")
    args = parser.parse_args()

    if args.info:
        pts = load_test_path(args.info)
        xs = [p[0] for p in pts]
        ys = [p[1] for p in pts]
        print(f"{args.info}: {TEST_PATHS[args.info]}")
        print(f"  file:    {_find_csv(args.info + '.csv')}")
        print(f"  points:  {len(pts)}   length: {path_length(pts):.2f} m")
        print(f"  bbox:    x [{min(xs):.2f}, {max(xs):.2f}]  y [{min(ys):.2f}, {max(ys):.2f}] m")
        markers = load_markers(args.info)
        print(f"  ground markers ({len(markers)}) -- pace these out from the rover's start pose:")
        for mid, mx, my, _ in markers:
            print(f"    #{mid}: x={mx:+.2f} m, y={my:+.2f} m")
        return

    have = set(available())
    print("Real-world test paths (rover-start-relative frame):\n")
    for name, desc in TEST_PATHS.items():
        mark = "  " if name in have else "! "
        print(f"{mark}{name:<20} {desc}")
    missing = [n for n in TEST_PATHS if n not in have]
    if missing:
        print(f"\n! = CSV missing ({', '.join(missing)}) -- run "
              f"{os.path.join(os.path.dirname(_SOURCE_DIR), 'generate_test_paths.py')}")
    print("\nDrive one with:")
    print("  ros2 launch aries_bringup full_hardware.launch.py test_path:=circle")
    print("  ros2 service call /planner/start std_srvs/srv/Trigger")


if __name__ == "__main__":
    _main()
